version: '3.5'
services:
    area_bdd:
        container_name: area_bdd
        image: postgres
        restart: always
        ports:
            - 5432
        env_file:
            - ./api/.env
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    area_app:
        container_name: area_app
        build:
            context: ./app
            dockerfile: Dockerfile
        volumes:
            - './app:/usr/src/app'
            - /usr/src/app/node_modules
        ports:
            - '8081:8081'
    area_api:
        container_name: area_api
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - './api:/usr/src/api'
            - /usr/src/api/node_modules
        ports:
            - '8080:8080'
        links:
            - area_bdd
        depends_on:
            - area_bdd
        environment:
            - NODE_ENV=development
    area_native:
        container_name: area_native
        build:
            context: ./native
            dockerfile: Dockerfile
        volumes:
            - './native:/usr/src/native'
            - /usr/src/native/node_modules